### ISSUE TITLE
Dosen't support 1.16.5 

### ISSUE THREAD

**Issue by Nobodyno-boop** [Klyser8/Iridescent#3]
Hi, 

The plugin dosen't support the 1.16.5.
Server: Paper version git-Paper-570 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

Just not works on the tchat.

We use essentials maybe the format break ur plugin?
With the `/msg * <@fire>` a work but it's a essentials command sound weird.

Edit: 
this plugin fuck all performance server (20 TPS with 50 players to 6 TPS.) Packet maybe not optimized

**Comment by fire** [comment]
Hello.

**Comment by Nobodyno-boop** [comment]
> Hello.

oh.. i'm sorry for this "ping" the "plugin" use this syntax...i forgot to put into code...
